### ISSUE TITLE
Depend on SLF4J instead of logback

### ISSUE THREAD

**Issue by msimav** [agourlay/cornichon#107]
SLF4J lets users choose implementation freely instead of forcing them to depend on logback

From [slf4j.org](http://slf4j.org):
> The Simple Logging Facade for Java (SLF4J) serves as a simple facade or abstraction for various logging frameworks (e.g. java.util.logging, logback, log4j) allowing the end user to plug in the desired logging framework at deployment time.

**Comment by agourlay** [comment]
your issue made do a quick scan of the codebase and actually Logback is not at all used (except for a logback.xml in the tests)

Scalatest is reponsible for the logging except in the case of error where the complete execution is "explained" using ```println```
https://github.com/agourlay/cornichon/blob/10ae154147332b9b56c239a05936ee2fc77047a1/src/main/scala/com/github/agourlay/cornichon/core/LogInstruction.scala#L28

I think I can remove the dependency completly and not even add the SLF4J dependency.

WDYT?

Thank you the report 👍

**Comment by msimav** [comment]
If removing it won't break anything, yeah, why not? 😄

**Comment by agourlay** [comment]
Let's see 🏭 

Another point, is this issue blocking you right now?

**Comment by msimav** [comment]
Nope, it isn't. I noticed it by chance and wanted to contribute.

**Comment by agourlay** [comment]
Already pushed a "fix" to master https://github.com/agourlay/cornichon/commit/2d2b15c046a1fd778a608adcc52ba0a9dd376c9c

I will do more testing later and hopefully release ```0.10.5``` beginning of January.

**Comment by agourlay** [comment]
fixed in 0.10.5
