### ISSUE TITLE
Usage of "assert" is confusing

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#20]
```Then assert``` is redundant. 

The usage of ```Then``` should be enough to infer that an assertion follows.

It should look more natural, something like:

```Then X is Y``` where X is a generic extraction and Y a value.

e.g ```Then status is 200```

Requires chaining of infix notation :  `obj method arg method arg method arg ...`

**Comment by cneijenhuis** [comment]
:+1: 
As I said after your talk, I find it redundant / hard to remember. Same for `debug` - if it says `show`, it implies that I want to `debug`.

**Comment by agourlay** [comment]
Somewhat fixed in 0.8.1 which replaced hadcoded linker words with a dynamic trait.

An extra word is still necessary to have proper infix notation, but now the user has more freedom, no need to remember it anymore.

Closing for now as it seems good enough.
