### ISSUE TITLE
Support GraphQL query AST as input

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#21]
JSON is cumbersome to write, it would be interesting to also support the GraphQL query AST as input.

```
 {
       id: 1
       name: "door"
       items: [
         # pretty broken door
         {state: Open, durability: 0.1465645654675762354763254763343243242}
         null
         {state: Open, durability: 0.5, foo: null}
       ]
}
```

ref https://github.com/sangria-graphql/sangria/commit/1998e0f4c0276e36e1da45ea266c56969ae59f92#diff-cf4a54c5a5ef49edc6332de99a35377aR34

**Comment by OlegIlyenko** [comment]
:+1:
