### ISSUE TITLE
containsExactly matcher on array

### ISSUE THREAD

**Issue by yanns** [agourlay/cornichon#370]
When using `asArray`, one has the choice to use `.asArray.is(theExpectedArray)`  that accept one element (expected array).
One can also use `.asArray.contains(element1, element2)` that accept multiple elements.
But `.asArray.contains(element1, element2)` matches even if the array contains 3 elements.

What would be useful would be a match accepting multiple elements and checking that the array contains exactly the elements given as parameter.
`.asArray.containsExactly(element1, element2)` would not match if the array contains `element1`, `element2` and also `element3`.

**Comment by agourlay** [comment]
This sounds reasonable 👍

**Comment by agourlay** [comment]
I did a quick implementation that reuses the non-ordered array equality infrastructure.
This means the error message is more generic than the custom one made for `contains` but I don't think it will be an issue in practice.
