### ISSUE TITLE
Request Content-Type Header is Overridden

### ISSUE THREAD

**Issue by xsoufiane** [agourlay/cornichon#377]
I believe there is an issue that results in overriding the headers before they get shipped. In particular, I have a request with a header *"Content-Type" -> "application/x-www-form-urlencoded"* but at the platfom level I receive *"Content-Type" -> "application/json"* :(

**Comment by agourlay** [comment]
Thank you for report, I have found the issue.
I will try to come up with a fix a publish a release soon.
