### ISSUE TITLE
Investigate migration to http4s-ember

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#391]
`Blaze` will be replaced by `Ember` according to the `http4s` team.

Let's give it a try.

- https://github.com/agourlay/cornichon/pull/427
- https://github.com/agourlay/cornichon/pull/428

It might hopefully fix the long standing issue with
```
java.lang.IllegalStateException: Cannot have multiple pending reads
```

**Comment by yanns** [comment]
I've opened https://github.com/http4s/http4s/issues/4525

**Comment by agourlay** [comment]
The Ember server PR has been finally merged and will be part of the next release.

The last missing bit to fix the migration was the usage of `.withShutdownTimeout()` to shorten the time to wait for a graceful shutdown.

**Comment by agourlay** [comment]
Client side coming in 0.21
