### ISSUE TITLE
Table tennis opponents are #weak

### ISSUE THREAD

**Issue by JulianSamarjiev** [agourlay/cornichon#50]
Fix this asap, or you will have no chance

@agourlay

**Comment by agourlay** [comment]
![lonely player](http://img.memecdn.com/Forever-Alone-Table-Tennis_o_104935.jpg)

**Comment by agourlay** [comment]
fixed in 0.6.0 - found some people to kick my ass :boom:

**Comment by JulianSamarjiev** [comment]
GG
