### ISSUE TITLE
no logo, no website => slacking

### ISSUE THREAD

**Issue by JulianSamarjiev** [agourlay/cornichon#54]
@agourlay

**Comment by OlegIlyenko** [comment]
+1

**Comment by agourlay** [comment]
I already have an issue for the website https://github.com/agourlay/cornichon/issues/14
I don't have the motivation right now but I do know that it is really important!

Concerning the logo I was in contact with a promising designer from Berlin who enjoys drinking sangria for breakfast but we did not find a suitable artistic direction :bowtie:

**Comment by JulianSamarjiev** [comment]
@agourlay Still slacking I see

**Comment by onibox** [comment]
@JulianSamarjiev PRs are welcome ;-)

**Comment by JulianSamarjiev** [comment]
@agourlay This can be closed now, only due to the Batman references :+1:

**Comment by agourlay** [comment]
As there is already a ticket for the website #14 , I created an issue for the logo as well #67 
Let's brainstorm ideas there ;)
