### ISSUE TITLE
save_body_key should evaluate JsonPath

### ISSUE THREAD

**Issue by cneijenhuis** [agourlay/cornichon#55]
`save_body_key("addresses[0].id" -> "customer-address-id")` does not work, as the JsonPath `"addresses[0].id"` is not properly evaluated.

(FYI: `body.path("addresses[0].id").is("test")` does work)

**Comment by agourlay** [comment]
The step you are looking for is already present under the name ```save_body_path```

But I understand that this is very misleading as the current implementation of ```save_body_key``` only accept root keys as strings.

What I propose is to replace the implementation of ```save_by_key``` by ```save_body_path```.
WDYT?

**Comment by cneijenhuis** [comment]
Well, then it's maybe more of a documentation problem because I didn't know there was a `save_body_path` :wink: 

But maybe it's indeed not necessary to have two different methods, as `key` is just a very simple `path`, right?

Somewhat related (but maybe worth an extra issue): Inside JSON, it would be cool if we could use the path as well. E.g.

```
{
  "address-id": "<addresses[0].id>"
}```

Then we probably need to save it into the session in the first place.

**Comment by agourlay** [comment]
Yes a ```key``` is a really simple path, so let's remove duplication.

Concerning your second question, yes it needs to be in session. 
Where is currently located your ```addresses``` object?

Most of the time you always extract the body of the response using the ```extractor``` option of the Http service.

For instance if your array of addresses is inside a person object in session you could write
```
{
  "address-id": "<person.addresses[0].id>"
}
```
