### ISSUE TITLE
Annotation to ignore Feature and Scenario

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#59]
It is already possible to ignore Features and Scenarios by passing ```ignore = true``` to the DSL builder.

It would be nice to do it just with an annotation as well.

```
class CornichonExamplesSpec extends CornichonFeature {

  lazy val feature =
    @Ignore
     Feature("Cornichon feature example") {

      @Ignore
      Scenario("demonstrate CRUD features") {
      ...
      }
```

**Comment by agourlay** [comment]
not really necessary - reopen on demand

**Comment by OlegIlyenko** [comment]
I was thinking about it... what can improve a dev flow is something like `@ExecuteOnlyThisScenarioAndIgnoreAllOthers`, especially for big files. More often than not, when I work on scenario, I'm not interested in other scenarios in the file.  When I want to test it, all other scenarios are also executed. If it's a big feature, it can take a while and it's nor really useful in this particular flow.

**Comment by OlegIlyenko** [comment]
my dream is just to write `~test` at the start of the day, and then use `@ExecuteOnlyThisScenarioAndIgnoreAllOthers` to control which tests are executed :)

I find `-t "My feature should my scenario"` too cumbersome to use, so in these cases it's faster for me to just comment out all other tests :)
