### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#67]
Let's brainstorm ideas for the creation of a nice logo.

**Comment by JulianSamarjiev** [comment]
@agourlay Still slacking I see

**Comment by agourlay** [comment]
@JulianSamarjiev I am currently busy tackling real important issues such as...changing the Json library :neckbeard:

**Comment by JulianSamarjiev** [comment]
@agourlay priorities.....

**Comment by OlegIlyenko** [comment]
@JulianSamarjiev if you have ideas for a logo design for the project, it would be great if you could share them. Any contributions in this respect are very welcome.

**Comment by JulianSamarjiev** [comment]
@OlegIlyenko Let me meditate on it

**Comment by lufego** [comment]
I have made a quick sketch on two concepts here 😄

Just for fun:
<img width="439" alt="screen shot 2016-06-07 at 17 53 00" src="https://cloud.githubusercontent.com/assets/14938754/15864788/b43abdd4-2cd8-11e6-94c0-11130c2a0fb1.png">


And:

<img width="748" alt="screen shot 2016-06-07 at 17 50 11" src="https://cloud.githubusercontent.com/assets/14938754/15864678/4f1cf5ac-2cd8-11e6-9298-91b3822c38fa.png">

😄 😄 😄 😄 😄 😄 😄

**Comment by OlegIlyenko** [comment]
Just to for the sake of brainstorming, here are some of my ideas as well:

![cornichon-logos](https://cloud.githubusercontent.com/assets/156569/15865120/d43ce7dc-2cd9-11e6-8572-c1594bb5e94e.jpg)

**Comment by agourlay** [comment]
Guys you are awesome  :sparkling_heart:

@lufego I really like the first jar 👍 
@OlegIlyenko I think I prefer having the logo separated from the name itself. I really like the variation of the bugs.

Wild idea maybe it is possible to add a bug in the jar? :neckbeard: 

For the text itself I would prefer having all the letter with the same color.

**Comment by JulianSamarjiev** [comment]
As a product owner of the logo issue, I am very much liking the direction @lufego has taken, especially the second option. Maybe it would be an idea to take the cornichon out of the jar and replace the letter "I" with it.

**Comment by agourlay** [comment]
I am open to any suggestions exploring different directions especially that we now have professional frontend artist in the thread!

Acceptance criteria : It should look cool on a sticker 😁

**Comment by agourlay** [comment]
I am planning to work soon on the documentation website, therefore I believe it is time to revive this issue!

I still like the direction taken y @lufego and to keep the good ideas coming I spent some time on shutterstock to see what people are doing. Here are a couple of images I like.

1) I like the drawing style 
https://www.shutterstock.com/image-vector/pickle-208948117?src=qvw01OQ62hAJDsaS70XKqA-4-85

2) Flat stylish jar in the middle
https://www.shutterstock.com/image-vector/seamless-pattern-pickle-jars-fruits-vegetables-313111346?src=qvw01OQ62hAJDsaS70XKqA-9-38

3) Nice realistic drawing
https://www.shutterstock.com/image-vector/vector-set-hand-drawn-fresh-garden-205870237?src=qvw01OQ62hAJDsaS70XKqA-10-98

4) Good job on the jar's reflections
https://www.shutterstock.com/image-vector/canning-pickles-glass-jar-vector-illustration-149151602?src=qvw01OQ62hAJDsaS70XKqA-11-16

5) This one looks already like a sticker
https://www.shutterstock.com/image-vector/vector-set-veggie-icons-60861976?src=qvw01OQ62hAJDsaS70XKqA-11-20

6) Super simplistic and flat approach
https://www.shutterstock.com/image-vector/canned-cucumbers-icon-gray-background-green-554547541?src=wDaqGCCUioy2yrsqbsjzxw-7-96

7) Supermarket jar
https://thumb1.shutterstock.com/display_pic_with_logo/3682172/360686018/stock-vector-pickles-set-in-jars-pickled-realistic-vegetables-peas-mushrooms-olives-cucumbers-colorful-360686018.jpg

Anything you like here?
I am pretty open to home made creation as well!

**Comment by JulianSamarjiev** [comment]
@agourlay Longest logo creation process in history?

**Comment by agourlay** [comment]
@JulianSamarjiev possible but I intend to wrap up this process pretty soon 🔨

**Comment by lufego** [comment]
Well here goes my last two final versions for the logo:

<img src="https://cloud.githubusercontent.com/assets/14938754/22596336/7196d20e-ea2b-11e6-9196-5910f1189a9b.png" width="350">

or if you want it to be part of the text:

<img src="https://cloud.githubusercontent.com/assets/14938754/22596348/7ceeb2a2-ea2b-11e6-8eff-4609e6fb4d69.png" width="350">

**Comment by agourlay** [comment]
@lufego thank you very much for your contribution 👍 

I think I am now sold on the idea of having the logo and the text clearly seperated, so maybe the cornichon does not need to be so bent.

Which leads me to the second point.

Maybe I have a twisted mind but I feel like it slighty looks like a part of the male anatomy, maybe you could have a cornichon more like your first submission which looked less phallic :see_no_evil:

Otherwise, I am satisfied with this logo 👍

**Comment by agourlay** [comment]
I started to work on the doc website https://agourlay.github.io/cornichon/

I had fun with the colors and the logo to get something up and running quickly 😸

**Comment by agourlay** [comment]
@OlegIlyenko I changed the colors a bit and removed the ugly logo. In the absence of logo, the one from ```sbt-microsite``` is used.

**Comment by OlegIlyenko** [comment]
![cornichon-logo-1](https://cloud.githubusercontent.com/assets/156569/22780311/9a9e093c-eebe-11e6-89dc-0e1538c84900.png)

Here is another logo idea. In a spirit of [scala](https://cdn.tutsplus.com/net/uploads/2013/06/scala-400.jpg), [monix](https://monix.io) and some other project that use ribbon in logo.

**Comment by JulianSamarjiev** [comment]
@OlegIlyenko Niiiiice, smart one! And we avoid the PEN*S looking issue.

**Comment by agourlay** [comment]
@OlegIlyenko this is a master piece, it has a strong Scala feeling!

**Comment by agourlay** [comment]
It is finally time to close this issue! 🎉 💥 

I have decided to go for the latest submission from @OlegIlyenko due to its innovative nature and link to the Scala ecosystem.

I'd like to thank all the people involved in this logo brain storming session especially @lufego who provided several drafts to explore alternative design.

🙇
