### ISSUE TITLE
Testing of GraphQL features

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#69]
The GraphQL features are not properly tested and are mixed with the "rest" tests, it is a bit confusing.

We want to separate those test to improve clarity.

- create a proper GQL endpoint for the superheroes API.
- split GQL tests into a dedicated feature file.

**Comment by OlegIlyenko** [comment]
👍

**Comment by agourlay** [comment]
Thx for your help 🙇 
Next step is mutation!
