### ISSUE TITLE
0.21 whish list

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#780]
The 0.20 series is almost 3 years old, it is time to plan 0.21 and discuss what could be done allowing breaking changes.

- Switch to Ember client https://github.com/agourlay/cornichon/pull/427
  - Not breaking but potential unknown issues regarding the new networking layer

- Change semantic of `Eventually` step to not accumulate the precise history
  - See discussion https://github.com/agourlay/cornichon/pull/778#issuecomment-1596167577
  - Should this be applied to other wrapper step?

- `CornichonJson.parseDataTable` could return a `Vector` to accommodate for `Json.fromValues` 

Ping @yanns & @martinw-ct for ideas :)

**Comment by yanns** [comment]
What about https://github.com/agourlay/cornichon/issues/237 ?

**Comment by agourlay** [comment]
I think it should be fine, I have an idea how to get it done :+1:
