### ISSUE TITLE
Creating/Using Custom Resolver not finding implicit conversion

### ISSUE THREAD

**Issue by kylepotts** [agourlay/cornichon#92]
Hello I am trying to use my own custom Resolver. But the code doesn't seem to pick up the implicit conversion. Maybe I am doing it wrong? There was no documentation for it so I had to pick through the source. 

`  implicit val jsonResolvableForm = new Resolvable[JsValue] {
    def toResolvableForm(s: JsValue) = s.toString()
    def fromResolvableForm(s: String) = Json.parse(s)
  }`

I get the error 

> could not find implicit value for evidence parameter of type com.github.agourlay.cornichon.http.BodyInput[play.api.libs.json.JsObject]

**Comment by agourlay** [comment]
Hi @kylepotts 

If I understand correctly you are trying to to use the HTTP DSL with Play-json object as input.

To this you need to define an instance of ```BodyInput``` for ```JsObject```. 

In practice ```BodyInput``` is ```Resolvable``` + ```Show```, as you already have a ```Resolvable[JsValue]``` you could try to define an implicit for ```Show[JsObject]```.

By default only those ```Show``` instances are in scope https://github.com/agourlay/cornichon/blob/master/src/main/scala/com/github/agourlay/cornichon/util/ShowInstances.scala

Usually people tend to use ```String``` as an input so I am interested to see how it goes for you. 
This part needs a better documentation indeed.

**Comment by kylepotts** [comment]
Correct I am trying to use a play json object. If you can programmatically create the json there is less chance of the json being malformed or incorrect so I wanted to give it a try.

I'll look into either make my own instance of body input or have a show. 

Thanks for this awesome library by the way! I am really enjoying how easy it is to make my own dsl around it.

**Comment by agourlay** [comment]
Thanks for the kind words.

You are right about creating json object directly it reduces the likelyhood of having malformed json. FYI we are using string input at my workplace and it practice it works rather well as the library offers a quick feedback cycle.

Anyway the library was designed to be flexible in order to appeal to different populations (devs, QA and PO) so it pleases me to hear you are building a customisation on top it.

Keep me posted regarding your issue, so I know the best way to document this 👍

**Comment by kylepotts** [comment]
I am having trouble extending the BodyInput since it is a sealed class.

**Comment by agourlay** [comment]
Why do you want to extend ```BodyInput```? 
It is just an ```alias```, you just need to create an instance of ```Resolvable``` and ```Show```.

Concerning  the ```NPE``` it is likely an initialization issue, I would guess you have defined your jsObject input value as a ```val``` somewhere, try ```lazy val```.

If my guess is wrong you can share your code in this issue or in the [Gitter chat](https://gitter.im/agourlay/cornichon) and will check it out.

**Comment by kylepotts** [comment]
I'll shoot ya a message in gitter. But the code I am using is 

`  def login_as_user = EffectStep(
    title = "login as user",
    effect = http.requestEffect(
      request = post("blah").withBody(Json.obj(
        "email" -> "<email>",
        "password" -> "password"
      ))
    )
  )`

**Comment by agourlay** [comment]
We found two separate issues
- lack of documentation for custom BodyInput for this very ticket
- error during parsing of custom BodyInput as described https://github.com/agourlay/cornichon/issues/93

**Comment by agourlay** [comment]
#93 should be resolved in 0.9.1

**Comment by kylepotts** [comment]
Verified solved in #93. Here is the code I used to use the play json object. 

```
  lazy implicit val jsonResolvableForm = new Resolvable[JsObject] {
    def toResolvableForm(s: JsObject) = s.toString()
    def fromResolvableForm(s: String) = Json.parse(s).as[JsObject]
  }

  lazy implicit val showJson = new Show[JsObject] {
    override def show(f: JsObject): String = f.toString()
  }

  lazy implicit val JsonEncoder:Encoder[JsObject] = new Encoder[JsObject] {
    override def apply(a: JsObject): cJson = parse(a.toString()).getOrElse(cJson.Null)
  }
```

**Comment by agourlay** [comment]
Nice!
Can I use your ```JsObject``` typeclasses as an example in the documentation>

**Comment by kylepotts** [comment]
Yeah sure go ahead!
